# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

variables:
  GO_VERSION: "1.25"
  GOPATH: "$CI_PROJECT_DIR/.go"
  GO_BIN_DIR: "bin"
  GO_MAIN_DIR: "."
  GO_BUILD_ARGS: ""
  GO_COVER_PACKAGES: ""
  GO_BUILD_NAME: "$CI_PROJECT_NAME"
  SECRET_DETECTION_ENABLED: 'true'
  GITLAB_ADVANCED_SAST_ENABLED: 'true'
  SAST_EXCLUDED_PATHS: "$CI_PROJECT_DIR/.go/**,$CI_PROJECT_DIR/bin/**"
  CI_APPLICATION_REPOSITORY: "$CI_REGISTRY_IMAGE"
  CI_APPLICATION_TAG: 'latest'

secret_detection:
  stage: go-test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml

stages:
  - prepare
  - go-test
  - build-app
  - build-container
  - test

# Download dependencies
go_mod_download:
  image: "golang:${GO_VERSION}-alpine"
  stage: prepare
  script:
    - mkdir -p $GOPATH
    - go mod download
  cache:
    key: "${CI_PROJECT_NAME}-go"
    paths:
      - .go/pkg/mod/
  artifacts:
    expose_as: 'Go Mod Download'
    expire_in: 1 week
    paths:
      - .go/pkg/mod/
  rules:
    - exists:
        - '**/go.sum'

# Lint code
go_lint:
  image: "golangci/golangci-lint:latest-alpine"
  stage: go-test
  needs: [ ]
  rules:
    - exists:
        - '**/*.go'
  variables:
    CONFIG_FILE_LINK: "https://gitlab.com/gitlab-ci-utils/config-files/-/raw/main/Linters/.golangci.yml"
  before_script:
    - apk add jq
  script:
    - cp .gitlab/golangci.yml .golangci.yml
    # Write the code coverage report to gl-code-quality-report.json
    - golangci-lint run --output.code-climate.path=gl-code-quality-report.json
  after_script:
    # Print linting issues to stdout in the format: path/to/file:line description
    - cat gl-code-quality-report.json | jq -r '.[] | "\(.location.path):\(.location.lines.begin) \(.description)"'
  artifacts:
    expose_as: 'Go Lint Report'
    expire_in: 1 week
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
  allow_failure: true

# Unit tests with coverage
go_test:
  image: "golang:${GO_VERSION}-alpine"
  stage: go-test
  needs:
    - job: go_mod_download
      optional: true
  before_script:
    # Get list of packages, replace newline with comma, and remove training comma.
    - export GO_COVER_PACKAGES=$(go list ./... | tr '\n' ',' | sed 's/,$//')
    - go get github.com/t-yuki/gocover-cobertura@latest
  script:
    - go test -v -coverpkg="$GO_COVER_PACKAGES" -coverprofile=coverage.out -covermode=count ./... | tee tests.txt
    - go tool cover -func coverage.out
  after_script:
    # Generate Cobertura coverage report for GitLab
    - $GOPATH/bin/gocover-cobertura -by-files < coverage.out > coverage.xml
    # Generate HTML coverage report
    - go tool cover -html coverage.out -o coverage.html
    # Generate JUnit report for GitLab
    - go-junit-report < tests.txt > junit.xml
  coverage: '/total:\s+\(statements\)\s+\d+\.\d+%/'
  artifacts:
    expose_as: 'Go Test Coverage Report'
    expire_in: 1 week
    paths:
      - coverage.html
      - coverage.out
      - tests.txt
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: junit.xml
  rules:
    - exists:
        - "*.go"

# Race condition tests
go_test_race:
  image: "golang:${GO_VERSION}"
  stage: go-test
  needs:
    - job: go_mod_download
      optional: true
  variables:
    # cgo is required for -race.
    CGO_ENABLED: "1"
  script:
    - go test ./... -race
  rules:
    - exists:
        - "*.go"

# Check if go mod tidy produces any changes
go_mod_tidy:
  image: "golang:${GO_VERSION}-alpine"
  stage: go-test
  needs:
    - job: go_mod_download
      optional: true
  rules:
    - exists:
        - '**/go.sum'
  script:
    - |
      # Check if go mod tidy produces any changes
      if [ ! -f "go.mod" ]; then echo "go.mod file not found" && exit 2; fi
      cp go.mod go.mod.before
      cp go.sum go.sum.before
      go mod tidy
      diff go.mod.before go.mod && diff go.sum.before go.sum

# Job to check for available updates for any direct module dependencies.
go_mod_updates:
  image: "golang:${GO_VERSION}-alpine"
  stage: go-test
  needs:
    - job: go_mod_download
      optional: true
  allow_failure: true
  before_script:
    - apk add jq
  script:
    # Waiting on https://github.com/golang/go/issues/40364 to allow listing
    # only direct dependencies so don't have to check JSON.
    - |
      # Check for available updates to any direct module dependencies
      UPDATES=$(go list -u -m -json all | \
        jq -c -r 'select(.Update != null and .Indirect == null) | "\(.Path) \(.Version) [\(.Update.Version)]"')
      printf "$UPDATES\n"
      if [ $(echo $UPDATES | wc -w) != "0" ]; then exit 1; fi
  rules:
    - exists:
        - '**/go.sum'

# Build for current OS/arch
go_build:
  image: "golang:${GO_VERSION}-alpine"
  stage: build-app
  script:
    - export CGO_ENABLED=0
    - go build ${GO_BUILD_ARGS} -o ./${GO_BIN_DIR}/${GO_BUILD_NAME} ${GO_MAIN_DIR}
  artifacts:
    expose_as: 'Go Build'
    expire_in: 1 week
    paths:
      - ./${GO_BIN_DIR}/${GO_BUILD_NAME}*

# Build container
build-docker:
  stage: build-container
  image:
    name: martizih/kaniko:debug
    entrypoint: [""]
  variables:
    FF_KANIKO_OCI_STAGES: 'true'
  dependencies:
    - go_build
  before_script: []
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --cache=true
      --registry-mirror=mirror.gcr.io
      --compression=zstd
      --compression-level=1
      --compressed-caching=true
      --single-snapshot
      --annotation="org.opencontainers.image.title=$CI_PROJECT_NAME"
      --annotation="org.opencontainers.image.version=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
      --annotation="org.opencontainers.image.source=$CI_PROJECT_URL"
      --annotation="org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --annotation="org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      --annotation="org.opencontainers.image.ref.name=$CI_COMMIT_REF_NAME"
      --annotation="org.opencontainers.image.description=$CI_PROJECT_DESCRIPTION"
      --build-arg="APP_DIR=$GO_BIN_DIR"
      --build-arg="APP_BIN=$GO_BUILD_NAME"
      --context="$CI_PROJECT_DIR"
      --dockerfile="$CI_PROJECT_DIR/Dockerfile"
      --destination="$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH"
      --destination="$CI_REGISTRY_IMAGE:latest"
